<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
<title>404 - Page not found</title>
</head>
<style type="text/css">
	*{ padding:0; margin:0}
	body{font-family: Open Sans;}
	.header{ height:80px; border-bottom:1px solid #778cbf; background:#1c3f95; min-width:1170px;}
	.container{ width:1140px; margin:0 auto; padding:0 15px;}
	.left{ float:left; width:65%}
	#footer{ background:#202020; height:46px; min-width:1170px; background:#202020; height:46px; min-width:1170px; width:100%} 
	.right{ float:left; width:35%}
	.left img{ max-width:100%}
	.clear{ clear:both}
</style>
<body>
	<div class="header">
    	<div class="container"><a href="/" style="padding-top:5px; display:block"><img src="<?php echo URL_DEFAULT_IMAGE?>/404/logo.png" width="67" height="66" /></a></div>
    </div>
<div class="container" style="margin-top:20px; margin-bottom:20px;">
    	<div class="left"><img src="<?php echo URL_DEFAULT_IMAGE?>/404/img-404.png" /></div>
        <div class="right">
        	<h2 style="color:#1c3f95; font-size:57px;">SORRY !</h2>
        	<p style="color:#999999; font-size:24px;">We couldn't find the page you were <br />looking for.</p>
        </div>
        <div class="clear"></div>
        
    </div>
<div id="footer">&nbsp;</div>

</body>
</html>
